### ISSUE TITLE
computePercentageExplained: NaN

### ISSUE THREAD

**Issue by loretoparisi** [bitanath/pca#1]
Hello, I'm getting NaN by the `computePercentageExplained` api.
My input is a vector of about ~5K components.

```javascript
var vectors = PCA.getEigenVectors(hashes);
var first = PCA.computePercentageExplained(vectors,vectors[0]);
var topTwo = PCA.computePercentageExplained(vectors,vectors[0],vectors[1]);
```

both `first` and `topTwo` are `NaN` here, while eigen vectors size is fine.

Thank you.

**Comment by bitanath** [comment]
Will check this out.. Can I get a sample of your data?

**Comment by loretoparisi** [comment]
@bitanath yes! Here you are:
https://gist.github.com/loretoparisi/01d19c958ba89c1200eb029b178c6c06
Basically those hashes are taken every `SAMPLING_RATE / STEP` for a given sample rate and step. But from PCA perspective it's just a list of integer numbers that increases (with time).

**Comment by bitanath** [comment]
This is one case that I had not accounted for.

However, is this sure of what you're trying to achieve. A PCA run on a 1-D vector should ideally return the same 1-D vector. Does this match your expectation?

**Comment by bitanath** [comment]
Closing this since it does not seem to be a bug

**Comment by loretoparisi** [comment]
@bitanath yes, closing thank you.
