### ISSUE TITLE
Transforming new data into already fitted PCA

### ISSUE THREAD

**Issue by peregilk** [bitanath/pca#2]
I have some code that I really want to run in a browser, and your PCA javascript implementation seems to solve most of my issues.

However, I have a large fitted PCA model (2 dimensions - 100 items).

I want to use the same model and transform new datapoints into this space. Adding the new datapoint and recalculating PCA is not working for me.

In Python sklearn I could do pca.transform_fit(model), and then pca.transform([newpoint]).

How can I do this using your library?

**Comment by bitanath** [comment]
@peregilk Can I also get a sample set of data, and the current commands run in the library to accomplish this?

Just trying to understand the code changes that would need to happen

**Comment by peregilk** [comment]
@bitanath. Thanks for answering my question. I fixed the issue. It turned out to be totally unrelated to your software. It seems to work without any issues. Thanks a lot for your great work.
